#!/usr/bin/env python
#
# route-mover -- Associate a subnet with a new route table in AWS
# Created: Marcus Butler, 05-April-2017.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

from common import get_rtb_assoc, change_rtb
import sys

if len(sys.argv) != 3:
   print("Usage: route-mover <subnet-id> <route-table-id>")
   sys.exit()

rtb_assoc = get_rtb_assoc(sys.argv[1])

if change_rtb(rtb_assoc, sys.argv[2]):
    print("Successfully changed route table for " + sys.argv[1])
else:
    print("Error changing route table for " + sys.argv[1])



