#!/usr/bin/python
#
# route-mover -- Associate a subnet with a new route table in AWS
# Created: Marcus Butler <marcusb@marcusb.org>, 05-April-2017.
#

from common import get_rtb_assoc, change_rtb
import sys

if len(sys.argv) != 3:
   print("Usage: route-mover <subnet-id> <route-table-id>")
   sys.exit()

rtb_assoc = get_rtb_assoc(sys.argv[1])

if change_rtb(rtb_assoc, sys.argv[2]):
    print("Successfully changed route table for " + sys.argv[1])
else:
    print("Error changing route table for " + sys.argv[1])



